import{qs,qsa,el,html}from"./utils.js";import{API}from"./api.js";
const panels=["login","inbox","products","settings","advanced"];function show(p){panels.forEach(x=>qs("#panel-"+x).style.display=(p===x?"block":"none"))}
qsa(".sidebar .btn").forEach(b=>b.addEventListener("click",()=>show(b.dataset.panel)));show("login");
async function refreshSession(){const s=await API.session().catch(()=>({authenticated:false}));qs("#login-status").textContent="สถานะ: "+(s.authenticated?"ล็อกอินแล้ว":"ไม่ได้ล็อกอิน");return s}
qs("#btn-login").addEventListener("click",async()=>{const pass=qs("#admin-pass").value;try{await API.login(pass);await refreshSession();alert("ล็อกอินสำเร็จ")}catch{alert("รหัสผ่านไม่ถูกต้อง")}});
qs("#btn-logout").addEventListener("click",async()=>{await API.logout();await refreshSession();alert("ออกจากระบบแล้ว")});
async function loadProducts(){const list=qs("#prod-list");list.innerHTML="";const products=await API.listProducts().catch(()=>[]);products.forEach(p=>{const row=html`<div class="card"><strong>${p.id}</strong> — ${p.name} — ${p.price} <button class="btn outline">แก้ไข</button></div>`;row.querySelector("button").addEventListener("click",()=>fillForm(p));list.appendChild(row)})}
function fillForm(p){qs("#p-id").value=p.id;qs("#p-name").value=p.name;qs("#p-price").value=p.price;qs("#p-image").value=p.image;qs("#p-desc").value=p.description||""}
qs("#prod-form").addEventListener("submit",async e=>{e.preventDefault();const payload={id:qs("#p-id").value.trim(),name:qs("#p-name").value.trim(),price:Number(qs("#p-price").value),image:qs("#p-image").value.trim(),description:qs("#p-desc").value.trim()};await API.updateProduct(payload).catch(async()=>{await API.createProduct(payload)});await loadProducts();alert("บันทึกสินค้าแล้ว")});
qs("#p-delete").addEventListener("click",async()=>{const id=qs("#p-id").value.trim();if(!id)return;await API.deleteProduct(id);await loadProducts();alert("ลบสินค้าแล้ว")});
async function loadSettings(){const s=await API.getSettings().catch(()=>null);if(!s)return;qs("#s-name").value=s.name??"Lux Shirt";qs("#s-slogan").value=s.slogan??"Premium Shirts for Everyday Confidence";qs("#s-logo").value=s.logo??"./assets/lux-logo.svg";qs("#s-hero").value=s.hero?.image??"./assets/hero.svg";qs("#s-ig").value=s.socials?.ig??"";qs("#s-fb").value=s.socials?.fb??"";qs("#s-line").value=s.socials?.line??"";qs("#s-email").value=s.socials?.email??"";qs("#s-address").value=s.socials?.address??"";qs("#s-phone").value=s.socials?.phone??"";qs("#s-verify").checked=s.chat?.requireVerifyName??true}
qs("#settings-form").addEventListener("submit",async e=>{e.preventDefault();const payload={name:qs("#s-name").value,slogan:qs("#s-slogan").value,logo:qs("#s-logo").value,hero:{image:qs("#s-hero").value},socials:{ig:qs("#s-ig").value,fb:qs("#s-fb").value,line:qs("#s-line").value,email:qs("#s-email").value,address:qs("#s-address").value,phone:qs("#s-phone").value},chat:{requireVerifyName:qs("#s-verify").checked}};await API.updateSettings(payload);alert("บันทึกการตั้งค่าแล้ว")});
async function loadInbox(){const box=qs("#threads"),detail=qs("#thread-detail");box.innerHTML="";detail.innerHTML="";const threads=await API.listChats().catch(()=>[]);threads.forEach(t=>{const row=html`<div class="card"><strong>${t.customerName}</strong> <span class="muted">#${t.id}</span> <button class="btn outline">เปิด</button></div>`;row.querySelector("button").addEventListener("click",()=>openThread(t));box.appendChild(row)});
function openThread(t){detail.innerHTML="";detail.appendChild(html`<h4>สนทนากับ ${t.customerName} (#${t.id})</h4>`);const area=html`<div class="messages" style="border:1px solid #eef2f7;border-radius:12px;padding:12px;max-height:40vh;overflow:auto;"></div>`;t.messages.forEach(m=>area.appendChild(html`<div class="msg ${m.role==='admin'?'admin':'user'}">${m.text}</div>`));const form=html`<form style="display:flex;gap:8px;margin-top:8px;"><input type="text" placeholder="พิมพ์ข้อความตอบกลับ" style="flex:1;padding:10px 12px;border:1px solid #e1e8f1;border-radius:10px;"/><button class="btn" type="submit">ส่ง</button></form>`;form.addEventListener("submit",async e=>{e.preventDefault();const text=form.querySelector("input").value.trim();if(!text)return;await API.adminReply(t.id,text);await loadInbox()});detail.appendChild(area);detail.appendChild(form)}}
qs('[data-panel="inbox"]').addEventListener("click",loadInbox);qs('[data-panel="products"]').addEventListener("click",loadProducts);qs('[data-panel="settings"]').addEventListener("click",loadSettings);refreshSession();
